// ECS utils
import * as utils from '@dcl/ecs-scene-utils'

// UI utils
import * as ui from '@dcl/ui-scene-utils'




let exhibition_texture_A1: Texture[] = [
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A1/1A-1-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A1/1A-1-2.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A1/1A-3-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A1/1A-3-2.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A1/1A-3-3.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A1/1A-4-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A1/1A-4-2.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A1/1A-4-3.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A1/1A-4-4.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A1/1A-4-5.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A1/1A-5-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A1/1A-5-2.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A1/1A-5-3.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A1/1A-5-4.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A1/1A-5-5.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A1/1A-5-6.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A1/1A-5-7.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A1/1A-6-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A1/1A-6-2.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A1/1A-6-3.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A1/1A-6-4.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A1/1A-7-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A1/1A-7-2.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A1/1B-1-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A1/1B-1-2.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A1/1B-3-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A1/1B-3-2.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A1/1B-3-3.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A1/1B-4-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A1/1B-4-2.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A1/1B-4-3.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A1/1B-4-4.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A1/1B-4-5.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A1/1B-5-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A1/1B-5-2.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A1/1B-5-3.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A1/1B-5-4.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A1/1B-5-5.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A1/1B-5-6.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A1/1B-5-7.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A1/1B-6-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A1/1B-6-2.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A1/1B-6-3.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A1/1B-6-4.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A1/1B-7-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A1/1B-7-2.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A1/1C-1-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A1/1C-3-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A1/1C-4-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A1/1C-4-2.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A1/1C-4-3.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A1/1C-5-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A1/1C-5-2.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A1/1C-5-3.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A1/1C-5-4.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A1/1C-5-5.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A1/1C-5-6.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A1/1C-6-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A1/1C-6-2.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A1/1C-6-3.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A1/1C-7-1.png"),
]







let exhibition_texture_A2: Texture[] = [
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A2/2A-1-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A2/2A-3-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A2/2A-5-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A2/2A-6-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A2/2A-6-2.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A2/2A-8-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A2/2A-9-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A2/2A-9-2.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A2/2A-9-3.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A2/2A-9-4.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A2/2A-11-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A2/2A-13-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A2/2A-14-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A2/2A-14-2.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A2/2A-15-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A2/2A-17-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A2/2A-20-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A2/2A-22-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A2/2B-1-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A2/2B-3-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A2/2B-5-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A2/2B-6-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A2/2B-6-2.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A2/2B-8-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A2/2B-9-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A2/2B-9-2.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A2/2B-9-3.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A2/2B-9-4.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A2/2B-11-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A2/2B-13-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A2/2B-14-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A2/2B-14-2.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A2/2B-15-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A2/2B-17-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A2/2B-20-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A2/2B-22-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A2/2C-1-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A2/2C-3-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A2/2C-5-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A2/2C-6-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A2/2C-6-2.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A2/2C-8-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A2/2C-9-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A2/2C-9-2.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A2/2C-9-3.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A2/2C-9-4.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A2/2C-11-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A2/2C-13-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A2/2C-14-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A2/2C-14-2.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A2/2C-15-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A2/2C-17-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A2/2C-20-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A2/2C-22-1.png"),
]




let exhibition_texture_A3: Texture[] = [
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A3/3A-2-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A3/3A-3-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A3/3A-3-2.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A3/3A-5-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A3/3A-5-2.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A3/3A-5-4.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A3/3A-6-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A3/3A-6-2.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A3/3A-6-4.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A3/3A-8-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A3/3A-9-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A3/3A-9-2.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A3/3A-9-3.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A3/3A-9-4.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A3/3A-10-1.png"),
]



let exhibition_texture_A4: Texture[] = [
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A4/4A-1-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A4/4A-2-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A4/4A-3-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A4/4A-4-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A4/4A-7-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A4/4A-8-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A4/4A-8-2.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A4/4A-9-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A4/4A-10-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A4/4A-10-2.png"),
]








let exhibition_texture_A6: Texture[] = [
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A6/6A-1-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A6/6A-1-2.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A6/6A-1-3.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A6/6A-1-4.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A6/6A-3-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A6/6A-4-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A6/6A-4-2.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A6/6A-4-3.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A6/6A-4-4.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A6/6A-7-1.png"),
    // new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A6/6A-7-2.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A6/6A-7-3.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A6/6A-10-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A6/6A-10-2.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A6/6A-10-3.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A6/6A-10-4.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A6/6B-1-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A6/6B-1-2.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A6/6B-1-3.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A6/6B-1-4.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A6/6B-3-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A6/6B-4-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A6/6B-4-2.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A6/6B-4-3.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A6/6B-4-4.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A6/6B-5-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A6/6B-7-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A6/6B-7-2.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A6/6B-7-3.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A6/6B-7-4.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A6/6B-9-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A6/6B-10-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A6/6B-10-2.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A6/6B-10-3.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A6/6B-10-4.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A6/6B-11-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A6/6C-1-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A6/6C-1-2.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A6/6C-1-3.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A6/6C-1-4.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A6/6C-4-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A6/6C-4-2.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A6/6C-4-3.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A6/6C-4-4.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A6/6C-7-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A6/6C-7-2.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A6/6C-7-3.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A6/6C-7-4.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A6/6C-10-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A6/6C-10-2.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A6/6C-10-3.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A6/6C-10-4.png"),
]






let exhibition_texture_A9: Texture[] = [
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A9/9A-2-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A9/9A-2-2.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A9/9A-2-3.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A9/9A-3-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A9/9A-3-2.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A9/9A-3-3.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A9/9A-4-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A9/9A-4-2.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A9/9A-4-3.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A9/9A-4-4.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A9/9A-5-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A9/9A-5-2.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A9/9A-5-3.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A9/9A-6-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A9/9A-6-2.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A9/9A-6-3.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A9/9A-6-4.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A9/9A-8-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A9/9A-8-2.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A9/9A-8-3.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A9/9A-9-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A9/9A-9-2.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A9/9A-9-3.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A9/9A-10-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A9/9A-10-2.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A9/9A-10-3.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A9/9A-11-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A9/9A-11-2.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A9/9A-11-3.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A9/9A-12-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A9/9A-12-2.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A9/9A-12-3.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A9/9A-12-4.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A9/9B-2-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A9/9B-3-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A9/9B-3-2.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A9/9B-4-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A9/9B-5-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A9/9B-6-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A9/9B-7-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A9/9B-7-2.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A9/9B-7-3.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A9/9B-8-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A9/9B-8-2.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A9/9B-8-3.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A9/9B-10-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A9/9B-10-2.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A9/9B-11-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A9/9B-11-2.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A9/9B-11-3.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A9/9B-12-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A9/9B-13-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A9/9B-14-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A9/9B-15-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A9/9B-15-2.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A9/9B-16-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A9/9B-16-2.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A9/9B-16-3.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A9/9C-2-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A9/9C-4-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A9/9C-6-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A9/9C-8-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A9/9C-10-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A9/9C-12-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A9/9C-14-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A9/9C-16-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A9/9C-18-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A9/9C-20-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A9/9D-2-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A9/9D-3-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A9/9D-4-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A9/9D-4-2.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A9/9D-4-3.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A9/9D-5-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A9/9D-6-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A9/9D-8-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A9/9D-9-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A9/9D-10-2.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A9/9D-10-3.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A9/9D-10-4.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A9/9D-11-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A9/9D-12-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A9/9E-2-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A9/9E-3-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A9/9E-4-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A9/9E-4-2.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A9/9E-4-3.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A9/9E-4-4.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A9/9E-4-5.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A9/9E-5-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A9/9E-6-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A9/9E-8-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A9/9E-9-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A9/9E-10-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A9/9E-10-2.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A9/9E-10-3.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A9/9E-10-4.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A9/9E-10-5.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A9/9E-11-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A9/9E-12-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A9/9F-2-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A9/9F-2-2.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A9/9F-3-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A9/9F-3-2.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A9/9F-4-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A9/9F-5-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A9/9F-6-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A9/9F-7-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A9/9F-8-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A9/9F-10-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A9/9F-11-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A9/9F-12-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A9/9F-13-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A9/9F-14-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A9/9F-15-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A9/9F-16-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A9/9G-2-1 .png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A9/9G-3-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A9/9G-5-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A9/9G-7-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A9/9G-8-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A9/9G-10-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A9/9G-11-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A9/9G-13-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A9/9G-15-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A9/9G-16-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A9/9G-16-2.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A9/9H-2-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A9/9H-2-2.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A9/9H-2-3.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A9/9H-3-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A9/9H-3-2.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A9/9H-4-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A9/9H-4-2.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A9/9H-4-3.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A9/9H-5-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A9/9H-5-2.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A9/9H-5-3.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A9/9H-5-4.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A9/9H-5-5.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A9/9H-5-6.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A9/9H-5-7.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A9/9H-5-8.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A9/9H-5-9.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A9/9H-5-10.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A9/9H-5-11.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A9/9H-5-12.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A9/9H-6-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A9/9H-6-2.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A9/9H-6-3.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A9/9H-7-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A9/9H-7-2.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A9/9H-7-3.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A9/9H-8-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A9/9H-8-2.png"),
]



let exhibition_texture_A10: Texture[] = [
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A10/10A-1-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A10/10A-1-2.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A10/10A-2-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A10/10A-4-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A10/10A-6-1.png"),
    new Texture("https://dcl-archverse.s3.us-east-2.amazonaws.com/A10/10A-8-1.png"),
]

export { exhibition_texture_A1, exhibition_texture_A2, exhibition_texture_A3, exhibition_texture_A4, exhibition_texture_A6, exhibition_texture_A9, exhibition_texture_A10 }