// ECS utils
import * as utils from '@dcl/ecs-scene-utils'

// UI utils
import * as ui from '@dcl/ui-scene-utils'

let exhibition_image:string[]=[
    "images/exhibition/A1/1A-1-1.jpg",
    "images/exhibition/A1/1A-1-2.jpg",
    "images/exhibition/A1/1A-3-1.jpg",
    "images/exhibition/A1/1A-3-2.jpg",
    "images/exhibition/A1/1A-3-3.jpg",
    "images/exhibition/A1/1A-4-1.jpg",
    "images/exhibition/A1/1A-4-2.jpg",
    "images/exhibition/A1/1A-4-3.jpg",
    "images/exhibition/A1/1A-4-4.jpg",
    "images/exhibition/A1/1A-4-5.jpg",
    "images/exhibition/A1/1A-5-1.jpg",
    "images/exhibition/A1/1A-5-2.jpg",
    "images/exhibition/A1/1A-5-3.jpg",
    "images/exhibition/A1/1A-5-4.jpg",
    "images/exhibition/A1/1A-5-5.jpg",
    "images/exhibition/A1/1A-5-6.jpg",
    "images/exhibition/A1/1A-5-7.jpg",
    "images/exhibition/A1/1A-6-1.jpg",
    "images/exhibition/A1/1A-6-2.jpg",
    "images/exhibition/A1/1A-6-3.jpg",
    "images/exhibition/A1/1A-6-4.jpg",
    "images/exhibition/A1/1A-7-1.jpg",
    "images/exhibition/A1/1A-7-2.jpg",
    "images/exhibition/A1/1B-1-1.jpg",
    "images/exhibition/A1/1B-1-2.jpg",
    "images/exhibition/A1/1B-3-1.jpg",
    "images/exhibition/A1/1B-3-2.jpg",
    "images/exhibition/A1/1B-3-3.jpg",
    "images/exhibition/A1/1B-4-1.jpg",
    "images/exhibition/A1/1B-4-2.jpg",
    "images/exhibition/A1/1B-4-3.jpg",
    "images/exhibition/A1/1B-4-4.jpg",
    "images/exhibition/A1/1B-4-5.jpg",
    "images/exhibition/A1/1B-5-1.jpg",
    "images/exhibition/A1/1B-5-2.jpg",
    "images/exhibition/A1/1B-5-3.jpg",
    "images/exhibition/A1/1B-5-4.jpg",
    "images/exhibition/A1/1B-5-5.jpg",
    "images/exhibition/A1/1B-5-6.jpg",
    "images/exhibition/A1/1B-5-7.jpg",
    "images/exhibition/A1/1B-6-1.jpg",
    "images/exhibition/A1/1B-6-2.jpg",
    "images/exhibition/A1/1B-6-3.jpg",
    "images/exhibition/A1/1B-6-4.jpg",
    "images/exhibition/A1/1B-7-1.jpg",
    "images/exhibition/A1/1B-7-2.jpg",
    "images/exhibition/A1/1C-1-1.jpg",
    "images/exhibition/A1/1C-3-1.jpg",
    "images/exhibition/A1/1C-4-1.jpg",
    "images/exhibition/A1/1C-4-2.jpg",
    "images/exhibition/A1/1C-4-3.jpg",
    "images/exhibition/A1/1C-5-1.jpg",
    "images/exhibition/A1/1C-5-2.jpg",
    "images/exhibition/A1/1C-5-3.jpg",
    "images/exhibition/A1/1C-5-4.jpg",
    "images/exhibition/A1/1C-5-5.jpg",
    "images/exhibition/A1/1C-5-6.jpg",
    "images/exhibition/A1/1C-6-1.jpg",
    "images/exhibition/A1/1C-6-2.jpg",
    "images/exhibition/A1/1C-6-3.jpg",
    "images/exhibition/A1/1C-7-1.jpg",
]
export {exhibition_image}